# CONFIGURAR A URL BASE DO SERVVIDOR OLLAMA
quarkus.langchain4j.ollama.base-url=http://localhost:11434/


# DEFINE O ID DO MODELO QUE O LANGCHAIN4J IRA INVOCAR NO OLLAMA
quarkus.langchain4j.ollama.chat-model.model-id=gpt-oss:20b


# DEFINE UM TIMEOUT PARA A CHAMADA.
# SE O MODELO DEMORAR MAIS DE 60S PARA RESPONDER, A CHAMADA FALHARÁ

quarkus.langchain4j.ollama.timeout=180s



# Apontando a pasta do easyrag

quarkus.langchain4j.easy-rag.path=src/main/resources/rag

